### ISSUE TITLE
Devel install

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#158]
Is it possible to install the Python part of `toast` in devel mode, as `pip install --editable .` so that it is not necessary to run `make` at each edit?

**Comment by tskisner** [comment]
Since we are not using setuptools, there is no "python setup.py --develop" mode.  Also, currently we use the build system to generate some files in the python package (for example, to hardcode the final install path of the library in the ctypes dlopen call.  This prevents having ctypes scan the entire LD_LIBRARY_PATH and instead just open the exact version of the library that it is supposed to.

Depending on future directions in the build system and wrapping the compiled code, we might be able to go back to this.  For example, pybind11 supports using cmake to build the compiled extensions while managing the top-level python package using setuptools.  However, this is further down the roadmap.

**Comment by zonca** [comment]
ok thanks
