### ISSUE TITLE
Timestamp repeats across observation

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#223]
I have hit a small issue on timestamps simulating PICO timelines for calibration work with @ziotom78 , it looks like the last sample of one observation and the next sample of the next observation have the same timestamp.

Last 2 samples of the first observation are:

    86399.99206349,  86400. 

The first 2 of the next:

     86400.        ,  86400.00793651

We have an interval of 0 between observations, is this the expected behavior?

**Comment by tskisner** [comment]
No, that is not the expected behavior.  I starting place to look is in the helper function used to compute those time ranges:

https://github.com/hpc4cmb/toast/blob/master/pipelines/toast_satellite_sim.py#L327
https://github.com/hpc4cmb/toast/blob/master/src/python/tod/sim_interval.py#L15

This takes the requested time ranges and then creates actual time spans that are a whole number of samples.

**Comment by zonca** [comment]
ok, I reproduced it in the simplest possible case: https://gist.github.com/zonca/6ace24831ad6fd0fb742cb426880d85c

Next I'll work on fixing it.
