### ISSUE TITLE
General focal plane configuration

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#252]
@tskisner Shaul at the telecon was asking if there is a way to generate a focal plane from a table of detectors position and orientation.
Last he asked @jdborrill, it was not possible in TOAST.

Here is a plot of the actual focalplane they would like to generate:

![screenshot 2018-07-09 at 18 20 06](https://user-images.githubusercontent.com/383090/42463659-0dafefe8-83a7-11e8-9f47-4b875dab0502.png)

**Comment by jdborrill** [comment]
I think we need to understand the driver for this.

If we can't simulate a year of data from the full focal plane, then this
level of detail is redundant. Even if we can, I want to know why PICO needs
this now (since this surely won't be the actual focal plane).

Julian

**Comment by tskisner** [comment]
We have functions to layout hex-packed detectors with a given plate scale and center offset quaternion.  We have similar functions for hexagons constructed from 3 rhombi.  The experiment-specific toast git repos have utility functions that piece these together to generate actual focalplanes.

There is no such thing as a "generic focalplane".  Creating them requires knowledge about the detector types in each pixel, where wafers containing particular pixel types should be placed, naming conventions, etc.

For example, for Simons Observatory, we have functions that take the pixel properties, bandpasses, etc and then lay out the wafers in each optics tube.

We could try to generalize things a bit more- for example, most experiments have "wafers" consisting of multichroic "pixels", each of which has some detectors in each "band" with some beam and orientation.  However, I don't think it will be possible to make something totally generic- one is always going to need some details about the instrument.

**Comment by hanany** [comment]
Hi Ted, given the focal plane you see in the image, what is the best way for you to implement it? As you can see, the inner wafers are hexagons, and the 3-color multi-chroic pixels (MCP) in them are laid out on a hexagon pattern. The outer 'ring' are not pure hexagons, but the MCP layout is ... well, you see what it is. 

Of course, we can provide coordinate for all the pixels.

**Comment by tskisner** [comment]
Well, I think the main question comes back to the issue raised by @jdborrill.  At this stage in the project, the big questions being addressed by time domain simulations are things like:

1. Impact of scan strategy choices on coverage, pixel condition number, leakage, etc.

2. Impact of relative detector counts at the different frequencies and where pixels of different types are placed in the field of view.

3. Impact of other hardware properties like detector noise models, existance and movement of a HWP, etc.

Given those goals, I would guess what is needed is an approximate focalplane layout that is realistic in terms of where different pixel types are located in the field of view.  The exact offsets of detectors within a wafer, or the spacing between wafers, etc is a small perturbation.

Recall that we already have a toast-pico git repo with our current model of the PICO focalplane:

https://github.com/hpc4cmb/toast-pico

If that model has changed in a dramatic way that impacts the 3 points above, then the code should be updated.  We don't currently have a function to do the "squashed hexagon layout" of the wafers around the edge of the field of view, so someone would have to write that.

**Comment by tskisner** [comment]
Just a reminder of what the current generated focalplane looks like in toast-pico.
![pico_hardware_lowres](https://user-images.githubusercontent.com/84221/42478182-9d2bbedc-8388-11e8-8059-dddaaad69d8e.png)

**Comment by hanany** [comment]
The focal plane we now have is obviously quite different compared to what Julian put in some months ago (just look at the two versions...). Already then we knew it was, and would continue to be, different, but we agreed we needed something quickly to 'clean the pipes' and just get something running. We agreed that once the pipes are cleaned, we would look back at the issue of implementing the right focal plane. 

Yes, I agree that the key question is 'what is the ultimate goal'. At this point the answer is quite simple: to get a proper assessment of Q, U, and noise for PICO, rather than not for PICO. 

Please note that about a week or so ago I updated the detector counts [in this page](https://zzz.physics.umn.edu/ipsig/baseline) to their final version. The focal plane in the figure in the same page (from which your figure is taken) is not consistent with that final detector count. 

On the question of the 'squashed hexagons': can we provide a list of coordinates? Can the code ingest a list of coordinates for the pixels? If not, can it be made to ingest a list of coordinates?

**Comment by tskisner** [comment]
Toast 3.0 includes a Focalplane class which can hold any detector properties that can be stored in an astropy Table.
