### ISSUE TITLE
Simplify python development

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#276]
There are 2 features used a lot by Python developers that I don't know if we can achieve with the TOAST build system:

* equivalent of `python setup.py develop`, we have a `setup.py` but in my understanding it disables MPI. Do you recommend to use this anyway and then test with MPI later?
* Fallback to debugger in failing tests: running `py.test --pdb`, you get a debugger into the failing unit test, can I do this in TOAST?

**Comment by zonca** [comment]
I tried `python setup.py develop` but fails with:

```
[ 76%] Built target toast_test
[100%] Built target _libtoast
copying /home/zonca/zonca/p/software/toast/build/temp.linux-x86_64-3.6/src/toast/_libtoast.cpython-36m-x86_64-linux-gnu.so -> /home/zonca/zonca/p/software/toast/src/toast
error: can't copy '/home/zonca/zonca/p/software/toast/build/temp.linux-x86_64-3.6/src/toast/_libtoast_mpi.cpython-36m-x86_64-linux-gnu.so': doesn't exist or not a regular file
```

**Comment by tskisner** [comment]
The official toast build system is the cmake one.  The current setup.py file simply runs the cmake build system.  It is useful for installing a bare-bones toast without MPI.  Here are some notes:

-  The reason MPI is disabled when using setup.py is that the user community has demonstrated that most people don't have a consistent installation of MPI plus a working mpi4py that is built with that same MPI.  For conda packages, we could enable MPI since we can then guarantee consistency between the two.  And for advanced users that know their installation of MPI and mpi4py are consistent, they can just run the real cmake build system.

- The "develop" target might be support-able.  We might need to implement that manually to symlink back to the cmake build directory.  However, remember there is compiled code.  Any time that changes you would need to rebuild.  How is that triggered?  I guess the user re-runs the develop command?

- For unit tests, the current test runner is MPI aware.  What happens when multiple MPI processes spawn the debugger?

**Comment by zonca** [comment]
At least the debugger should work on serial mode. I am currently print-debugging, which is no fun.

**Comment by zonca** [comment]
I got around the `python setup.py develop` issue, I install the package with cmake, then symlink the python package into the site-packages folder.

**Comment by zonca** [comment]
`py.test` works fine with MPI, see for example https://github.com/healpy/pysm/blob/master/run_mpi_tests.sh

**Comment by tskisner** [comment]
Hi @zonca, toast uses the standard python unittest module.  The tests use a test runner which is very close to the default text runner except that there is an optional comm argument.  The tests are added manually to the test suite, rather than using auto discovery.  However, it's all just standard python unittest stuff.

What changes do you think are needed to support your use case?  Do you just want a "test" command added to setup.py?  Do you need some modifications to the toast.tests.run() function?

**Comment by tskisner** [comment]
As for the develop target, I agree we can add a custom command that basically does just what your workaround does- builds the software and then installs symlinks.
