### ISSUE TITLE
Integrate new total convolution/interpolation library?

### ISSUE THREAD

**Issue by mreineck** [hpc4cmb/toast#373]
Perhaps it's a good idea to switch from email exchange to discussing this here, where everyone interested can see it...

I'd be happy to contribute the new total convolution/interpolation library I implemented over the last year or so to Toast, with the long-term goal to supersede `libconviqt`. It basically has the same functionality, but is much more accurate and, at least for beams with high `m` modes, much faster (interpolation time is independent of the highest beam `m`). The interface provides functionality which allows distribution of the computational work using MPI, but the distribution has to be done on the caller's side, which is of course more work for the user, but also provides the maximum of flexibility. This is a part of the work where I probably won't be able to contribute much, as I'm not really familiar with Toast's inner structure.

The code (including a Python interface for simple testing) is available at https://gitlab.mpcdf.mpg.de/mtr/ducc. I'm painfully aware that C++ interface documentation is still nonexistent, but I hope to get this addressed very soon.

Please let me know what I can do to improve the chances of having this integrated into Toast!

[Edit: typos]

**Comment by mreineck** [comment]
Some data on the code:
- code size relevant for this functionality: approx. 10.000 sloc
- no external dependencies
- requires a C++17 compiler

**Comment by tskisner** [comment]
Hello @mreineck , thanks for opening an issue to track this.  As discussed offline, it will hopefully not take much work to call this from a toast workflow.  In toast there are a couple hundred lines of interface code that call `libconviqt`, but that package (including its mpi-aware python bindings) are not in our source tree, but rather an external package.

Your code is actually *easier* for us to use from a distribution perspective.  Toast intentionally keeps all MPI operations in python, rather than the compiled extension, so that it can be distributed as binary wheels on PyPI.  This use of MPI in compiled code is why we do not ship `libconviqt` and `libmadam` as part of our binary packages on PyPI.  Your code has no MPI in the compiled library, so we would be able to include that directly in the toast pip package (much as we currently bundle FFTW, SuiteSparse, and OpenBLAS).

In any case, we are in the process of a major version release which changes internal APIs, so I am guessing that work on this will not start for a couple weeks.

**Comment by mreineck** [comment]
> Your code has no MPI in the compiled library, so we would be able to include that directly in the toast pip package (much as we currently bundle FFTW, SuiteSparse, and OpenBLAS).

That makes perfect sense, and I'm happy now that I didn't spend time trying to get MPI parallelism in on the C++ side.

There is however another problem concerning binary wheels: achievable performance depends strongly on the available vector extensions, and I have not managed yet to come up with a way to do run-time dispatching of the appropriate functions. Currently the recommended way is to compile with `-march=native` on the target machine. If you have any recommendations concerning this topic, I'd be glad to hear them!

**Comment by tskisner** [comment]
We assume that users installing binary packages from PyPI or conda-forge are interested in ease of installation / maintenance rather than performance.  These are typically built inside manylinux docker containers (ancient CentOS) using older (gcc-8) compilers.  This provides maximum glibc compatibility across a range of linux distros.

For use at computing centers we always build from source, with newer compilers (usually gcc or Intel).

**Comment by mreineck** [comment]
OK, great! gcc 8 will work fine with the code (lowest working version is gcc 7). With the Intel compiler things could get a bit hairy, since the versions I tested didn't know about `std::any` and perhaps a few other C++17 features. However that may have changed in the meantime, and workarounds may also be possible.

**Comment by mreineck** [comment]
Concerning Intel compiler support: I managed to compile and successfully test the code using the "new" Intel compilers (see https://software.intel.com/content/www/us/en/develop/tools/oneapi/all-toolkits.html). Performance was worse than with `gcc` though.
Given that Intel appears to switch compiler atchitecture, I don't expect to get the code to run with the "traditional" compiler (i.e. `icpc`); it probably won' get the necessary updates.

**Comment by mreineck** [comment]
Just a heads-up: I'm making a very small interface change in the functions `getPlane` and `updateSlm`. They were taking separate `re` and `im` arguments (where `im` was only used for `mbeam>0`). I'm merging these into a single argument by introducing an leading array dimension with either  one or two entries. This should make the code easier to use, and also allows internal simplifications.

**Comment by mreineck** [comment]
In related news, @AdriJD and myself are thinking about how the totalconvolve library and the `hwp_syst` branch of https://github.com/AdriJD/beamconv/ can be combined for more realistic simulations including a HWP. This might also be of interest for `toast` in the slightly longer term.

**Comment by mreineck** [comment]
Now that libconviqt support is back in Toast 3, should I try to build an analogous operator for ducc0.totalconvolve? Most likely I won't be able to get it fully working all by myself, but at least I might save you some tadious work.
The only thing I'd need to get started is a small demo/test case for Toast 3 that exercises the current libconviqt operator, so I can validate the new code against it.

**Comment by tskisner** [comment]
Thanks for working on this @mreineck !  It was on the to-do list of @keskitalo, so I am sure he appreciates it :-)

**Comment by mreineck** [comment]
Experimental version in #387.

**Comment by mreineck** [comment]
I'm perfectly happy to do as much as I can on my part, but I'm pretty sure there are many details which require more Toast knowledge than I have.
Things seem to run now, which is encouraging :-)

**Comment by keskitalo** [comment]
Thanks @mreineck. This is awesome! I made some comments on your pull request. Please also run `src/format_source.sh`. The biggest question is whether there needs to be two versions of the operator like with `conviqt`.

**Comment by mreineck** [comment]
I agree that one version of the operator should be enough. Will have a closer look at this soon.

**Comment by mreineck** [comment]
I think this can be closed.
