### ISSUE TITLE
Extend the logger to support *args

### ISSUE THREAD

**Issue by ickc** [hpc4cmb/toast#411]
I found that Python logger has additional arguments such that the string with not be formatted if the log level is higher: https://docs.python.org/3/library/logging.html#logging.debug

But then I found that the toast logger only supports the first argument of the Python logger.

MWE:

```python
from logging import getLogger

logger = getLogger('pantable')
logger.warning('abc: %s, %s', 'efg', 'hij')
# ok: abc: efg, hij
```

```python
from toast.utils import Logger

logger = Logger.get()
logger.warning('abc: %s, %s', 'efg', 'hij')
# not ok
```

The advantage of `*args` is that when the log level is not needed, the string is not constructed in the first place. So for example

```python
logger.debug('this dictionary is ok: %s', medium_sized_data)`
```

would not have constructed a long string if the log level is higher than DEBUG.

**Comment by tskisner** [comment]
There is one technical reason and one design reason against this proposed change.  

The technical reason is that the toast logging facilities are actually a wrapper around the C++ Logger class.  This allows us to unify log messages from across the C++ and Python source (i.e. they are dumped out in sequence to C stdout).  The python string passed into the logging methods is passed to compiled code.   So even if we supported `*args` in the python interface, we would always have to form a string anyway to pass it to C++.  Or we would have to add additional logic in the python method that checked the log level before calling the compiled code (that logic is already in the compiled code, checking the log level to decide whether to print something).

The design reason comes down to the intended purpose of the Logger.  At INFO level, the statements should be minimal and coming from at most one process per group or one global process.  At DEBUG level, there will be more statements but still from a subset of processes.  At VERBOSE level there are a huge number of things printed, but frequently still from a subset of processes.  However, one **could** consider printing a small number of VERBOSE statements from all processes.  VERBOSE log level should never be used in production jobs, since writing many thousands of things to stdout does have a large cost.  Even at "verbose" log level, if just formatting a string impacts the performance of the code, then it means that this logging statement is someplace where it does not belong.  For example, inside a tight loop without much other work and being called thousands of times.  If one is debugging code like that, then using an interactive debugging session might be better, or if you do insert a print / logging statement for debugging, comment it / remove it afterwards.

The same design philosophy applies to the toast timing classes- these are intended to give big-picture information of what is going on.  If one is trying to optimize a small kernel that is called many times, then a profiler should be used, not the timing classes.
