### ISSUE TITLE
How to install cmbenv-intel_20210527 in /global/common/software/** at NERSC?

### ISSUE THREAD

**Issue by yoshinori-0778** [hpc4cmb/toast#414]
Dear all,

I'm one of the members in GroundBIRD experience.
I would like to install cmbenv-intel_20210527 in /global/common/software/** at NERSC in order to modify the code for our experience(GroundBIRD).
I'm trying now while refering to "Installing TOAST (Optional)" on your document(https://github.com/hpc4cmb/toast/blob/master/docs/nersc.rst).
However, I don't understand 2nd and 3rd procedures; 
2, Load the cmbenv stack.
3, Go into your git checkout of TOAST and make a build directory:

How to load cmbenv stack(cmbenv-intel_20210527 for my case) in /global/common/software/** ?
Could you explain these procedures in more detail?
I would be happy to get some example commands.

Best Regards.
Yoshinori SUENO

**Comment by giuspugl** [comment]
Hello, 
Did you check the documentation page ? 
https://toast-cmb.readthedocs.io/en/latest/nersc.html#nersc

**Comment by yoshinori-0778** [comment]
Hello, 
Thank you for your reply.

Yes, I have checked that page.
But, I did not understand how to load the cmbenv stack (2nd procedure on Installing TOAST (Optional)).

**Comment by tskisner** [comment]
If you want to install your own copy of toast at NERSC, you should just load the existing cmbenv stack and compile toast.  You do not need to install a copy of the full cmbenv stack (that is a much larger task, and not part of toast).  The point (2) which says "load the cmbenv stack" is referring to the previous sections:
```
module use /global/common/software/cmb/${NERSC_HOST}/default/modulefiles
module load cmbenv
source cmbenv
```
So you are just using those pre-installed tools.  This stack includes a version of toast.  Installing your own copy of toast is only needed if you want to hack on the source code, and steps 3-5 describe how to do that and load your copy of toast into your environment so that it is found before the copy of the toast in the cmbenv stack.

**Comment by yoshinori-0778** [comment]
Thank you for your answer.

I can understand how to do step2, and I could load the existing cmbenv stack and use toast.
However, I cannot rewirte the loaded toast code due to the permission.(toast path : /global/common/software/cmb/cori/cmbenv-intel_20210527/cmbenv_aux/lib/python3.7/site-packages/toast)
We think this is natural since we are using global toast.

What I want to do is to rewrite (modify) the script in the toast in order to optimize them for our experience.
So I think I have to Install TOAST in /global/common/software/**.

> steps 3-5 describe how to do that and load your copy of toast into your environment so that it is found before the copy of the toast in the cmbenv stack.
I want to do step 3, but I don't understand that 'Go into your git checkout of TOAST and make a build directory.
This is because I cannot mkdir build in the toast path written above due to permission.
I also cannot find toast in /global/common/software/** or my home directory just doing "load the cmbenv stack"
Therefore I am confusing.
Where should I go? What dose 'Go into your git checkout of TOAST' mean?

I really appreciate your precious time.

**Comment by tskisner** [comment]
You need to clone this git repository (`git clone git@github.com:hpc4cmb/toast.git`) into your home directory at NERSC.  If you are modifying the toast source then you should have your own copy of the source.  You should be using your own git checkout of toast if you are making modifications.  Then you should install that to some other prefix (like in your home directory) using the instructions in that web page (compiling toast, installing to someplace, creating a shell function to load it, etc).  You do not need to install software to `/global/common/software` unless you are running on many nodes.  Installing to your home directory is fine.  You should install to a **different** directory than your git checkout.

**Comment by ickc** [comment]
Another way of doing this is to clone the [cmbenv repo](https://github.com/hpc4cmb/cmbenv.git) directly. And then run `./cmbenv` in that directory. E.g. `./cmbenv -c cori-intel -p /global/common/software/......`. This is how I use it in the past. You'd probably want to use one of the release tag in <https://github.com/hpc4cmb/cmbenv/releases>.

Installing at NERSC is more complicated as that requires custom Cray wrapper for MPI, etc.
Depending on your use cases, and if you're willing to install on your local machines for testing first, I have other scripts that helps installing a developing toast stack. Let me know if you need that.

**Comment by yoshinori-0778** [comment]
Dear all, 
Thank you for reply.
I have tried two way as mentioned above.

1. git clone toast as written by Mr Theodore Kisner.
I could do git clone and build and make basically using the instructions in that web page.(Cmake version in NERSC is not enough to do this compile. So I install latest cmake in my home directory and compile the toast by using this cmake.)
However, when I try to import toast, module error is happened.(python modules imported with 'module load python')
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/homes/s/sueno/toast_install/lib/python3.6/site-packages/toast/__init__.py", line 41, in <module>
    from .mpi import Comm
  File "/global/homes/s/sueno/toast_install/lib/python3.6/site-packages/toast/mpi.py", line 11, in <module>
    from ._libtoast import Logger
ModuleNotFoundError: No module named 'toast._libtoast'
```
I have added the path to the installed toast correctly.
I also have checked toast/lib/*. And I confirmed that there is no `toast._libtoast` but `_libtoast.cpython-36m-x86_64-linux-gnu.so`.
Therefore, I guess I cannot uncompress this file correctly.
Is there any way to uncompress it ? or did I not build and make correctly?

2. git clone cmbenv as written by Kolen Cheung
I am just trying now and no error so far.(But it seems it will take a lot of time)
Thank you for your suggestion
>Depending on your use cases, and if you're willing to install on your local machines for testing first, I have other scripts that helps installing a developing toast stack. Let me know if you need that.
But unfortunately, I have not a PC which has enough spec to simulate.Therefore, I cannot do in my local machine now.
Anyway, Im also trying your suggested way in NERSC.

Best Regards.
Yoshinori

**Comment by tskisner** [comment]
Hello @yoshinori-0778 , if you cannot build toast using the existing `cmbenv` software stack, then you should not try to build the full set of dependencies from source (i.e. do not try and compile the full cmbenv tools from the beginning).  That is **much** more work than you need just to use a custom toast.  All of the toast dependencies are already installed and available.

The first clue is that you say, "Cmake version in NERSC is not enough to do this compile".  The fact that you get this error means that you do not have the `cmbenv` tools loaded, since they include a very recent version of cmake.  Can you please:

1.  Verify that your `~/.bashrc` file does not have any "module load" commands, so that when you log in your environment is the original one set up by NERSC.  If you have any module commands in this file, comment out those lines with a '#' character at the beginning of the line.  If you make changes to the file, log out and log back in.
2.  Execute the commands:
```
module use /global/common/software/cmb/${NERSC_HOST}/default/modulefiles
module load cmbenv
source cmbenv
```
3.  Please post the output of these commands:
```
which cmake
env | grep CMBENV
```
4.  Enter the directory where you have cloned toast and post the output of these commands:
```
pwd
git branch -a
git remote get-url origin
```
(that last command should display something like `git@github.com:hpc4cmb/toast.git`)
5.  When installing toast, make sure to install to a different directory than the git clone directory.  If you are in your git clone directory, do:
```
mkdir -p build
cd build
rm -rf *
../platforms/cori-intel.sh -DCMAKE_INSTALL_PREFIX=$HOME/toast_install
make -j 4 install
```
You can change the directory "toast_install" to something else, but do not install to the same place as your git clone directory.
6.  Now your copy of toast is installed to a directory, but you cannot use this until you load it into your environment.  Add a shell function as discussed in the documentation.  Edit your `~/.bashrc` file and add a function like this:
```
load_toast () {
    dir=$HOME/toast_install
    export PATH="${dir}/bin:${PATH}"
    pysite=$(python3 --version 2>&1 | awk '{print $2}' | sed -e "s#\(.*\)\.\(.*\)\..*#\1.\2#")
    export PYTHONPATH="${dir}/lib/python${pysite}/site-packages:${PYTHONPATH}"
}
```
**make sure to change `toast_install` to whatever location you used in the previous step**
7.  Log out and log back in.  Now load the cmbenv tools and then your custom toast installation:
```
module use /global/common/software/cmb/${NERSC_HOST}/default/modulefiles
module load cmbenv
source cmbenv
load_toast
```
8.  Verify that you are using **your** copy of toast:
```
python -c 'import toast; print(toast.__file__)'
```
This should print a path that is in `$HOME/toast_install` or whatever you used for the install prefix above.

**Comment by yoshinori-0778** [comment]
Dear  Theodore Kisner,

Thank you for presenting detail description.
I finally have done the install of toast following your explanation.
I have confirmed that toast can be imported correctly.(`$HOME/toast_install`)

And, I also have investigated `cmbenv` correctly as written by Kolen Cheung

I really appreciate your time and effort.

Best Regards.

**Comment by tskisner** [comment]
It seems like this was resolved, but feel free to reopen the issue if not.
